### ISSUE TITLE
Bug: fjump reopens a file that already is open

### ISSUE THREAD

**Issue by bjoerndemeyer** [serge-v/micro-quickfix#2]
Currently, when using fjump to jump to a file, it reopens a file that was already open. This makes it impractical to jump back and forwards often. It would be nice if that could be fixed.

**Comment by serge-v** [comment]
thanks for reporting. Fixed in https://github.com/serge-v/micro-quickfix/commits/v2.0.4

**Comment by raidenXR** [comment]
Did the latest update break that again? Version 2.1.0 has this issue. 
P.S quickfix is a great plugin nonetheless

**Comment by serge-v** [comment]
yes, it works only when jump line exactly matches the tab name. Ideally the plugin should use absolute paths to lookup the open tab. I'll fix it in the near future. Thanks for reporting.

**Comment by serge-v** [comment]
fixed in https://github.com/serge-v/micro-quickfix/tree/v2.1.2 .
