### ISSUE TITLE
Please add  the Placeholder. line number, column position 

### ISSUE THREAD

**Issue by usagi3000** [serge-v/micro-quickfix#3]
I like fexec.
I want the row number and column position of the cursor position.

fexec my_program linenumber columnPosition file

Please add the Placeholder:
{l} : linenumber
{c} : columnPositon

**Comment by serge-v** [comment]
thanks for the report. Added in https://github.com/serge-v/micro-quickfix/commits/v2.0.3

**Comment by usagi3000** [comment]
Thank you very much.

**Comment by usagi3000** [comment]
Thank you very much.
