### ISSUE TITLE
Quickfix Panel not Showing Errors

### ISSUE THREAD

**Issue by raidenXR** [serge-v/micro-quickfix#4]
I tried the plugin with both C# and Zig. In both cases when an error occurs i.e in compilation, panel won't even show up but an `fexec error: exit status 1` instead.
In case of successful compilation in C#, panel will print the whole text, same as running the command in terminal.
In case of Zig:
   - successful compilation prints a blank panel,
   - successful `test` prints the the messages successfully, but failed test results in `fexec error: exit status 1`
   - successful `zig ast-check` prints blank panel and failed 'ast-check' results in `fexec error: exit status 1`

That's a bit weird. Why quickfix panel, has an issue with printing errors, and when no errors occur, in some cases prints the messages in panel, while in other case, it prints nothing and shows a blank panel?

**Comment by raidenXR** [comment]
I had a look into the code. I see that is a design choice?
Also, neither `micro.InfoBar():Message("running: "..cmd)` shows up when executing a command.

**Comment by serge-v** [comment]
yes, it should show the output regardless of exit code.
Fixed in v2.0.5. Thanks for reporting.

**Comment by raidenXR** [comment]
yes, I tested it and now prints the messages accordingly on all the cases I reported earlier!
